name: Blackduck
on:
  push:
    branches: [main, task/add-blackduck]
  pull_request:
    branches: [main, task/add-blackduck]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.6.0
        env:
          DETECT_PROJECT_NAME: "MED_acme-dns-azure"
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackduck_scan_failure_severities: "BLOCKER,CRITICAL"

          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackduck_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled

          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackduck_prcomment_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled
